name: ubuntu

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup g++
      run:
        sudo apt update
        sudo apt install g++

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./viper_tests

